### ISSUE TITLE
TypeError on finding cards

### ISSUE THREAD

**Issue by hiteshgarg14** [VirgilSecurity/virgil-sdk-python#17]
I am using
-  python 2.7.12 
- virgil-crypto==2.3.0
- virgil-sdk==4.2.2

I am running this code

```
virgil = Virgil("AT.KEY")
virgil.cards.find(["Hello"])
````
and getting below error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/local/lib/python2.7/site-packages/virgil_sdk/api/card_manager.py", line 101, in find
    founded = self.context.client.search_cards_by_identities(identities)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/local/lib/python2.7/site-packages/virgil_sdk/client/virgil_client.py", line 193, in search_cards_by_identities
    SearchCriteria.by_identities(identities)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/local/lib/python2.7/site-packages/virgil_sdk/client/virgil_client.py", line 220, in search_cards_by_criteria
    response = self.read_cards_connection.send_request(http_request)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/local/lib/python2.7/site-packages/virgil_sdk/client/http/base_connection.py", line 68, in send_request
    response = urllib2.urlopen(prepared_request, context=ctx)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: JSON specified as a request is invalid
```

But If I try it with `virgil.cards.find("Hello")` then it gives list as output. I have gone through documentation and code and it says that the input should be `the list of sought identities`.

**Comment by Imelstorm** [comment]
Fixed in 4.2.3 version
