### ISSUE TITLE
TypeError on publishing card

### ISSUE THREAD

**Issue by hiteshgarg14** [VirgilSecurity/virgil-sdk-python#18]
I am using
-  python 2.7.12 
- virgil-crypto==2.3.0
- virgil-sdk==4.2.2
- ubuntu 16.04 LTS and Mac OSX High Sierra 10.13.4 (17E199)

I am trying to publish the card as given below

Client Side :-
```
alice_key = virgil_client.keys.generate()
alice_key.save("Key_Name", "Password")
alice_identity = virgil_client.identities.create_user("Hello", 'test_user')
alice_card = virgil_client.cards.create(alice_identity, alice_key)
exported_alice_card = alice_card.export()
```
Server Side :-
```
original_card = virgil.cards.import_card(exported_alice_card)
virgil.cards.publish(original_card)
```

and I am getting below error

```
Traceback (most recent call last):
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hitesh/Documents/WorkSpace/virgil/server.py", line 41, in home
    virgil.cards.publish(original_card)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/virgil_sdk/api/card_manager.py", line 147, in publish
    card.publish()
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/virgil_sdk/api/virgil_card.py", line 169, in publish
    self.__context.credentials.get_app_key(self.__context.crypto)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/virgil_sdk/client/request_signer.py", line 73, in authority_sign
    signable_request.snapshot
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/virgil_sdk/cryptography/crypto.py", line 404, in calculate_fingerprint
    hash_data = self.compute_hash(data, HashAlgorithm.SHA256)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/virgil_sdk/cryptography/crypto.py", line 422, in compute_hash
    return native_hasher.hash(data)
  File "/home/hitesh/Documents/WorkSpace/virgil/venv/lib/python2.7/site-packages/virgil_crypto/virgil_crypto_python.py", line 934, in hash
    return _virgil_crypto_python.VirgilHash_hash(self, data)
TypeError: in method 'VirgilHash_hash', argument 2 of type 'virgil::crypto::VirgilByteArray const &'
```

**Comment by Imelstorm** [comment]
Fixed in 4.2.3 version
